openapi: 3.0.0
info:
  title: "API"
  version: "1.0.0-alpha"
tags:
  - name: SSTS API
    description: Identification API by facial recognition
paths:
  /:
    get:
      operationId: index
      description: API Greeting Point
      summary: Get a greeting message
      tags: ['Index' ]
      responses:
        '200':
          description: The greeting message
          content:
            text/plain:
              schema:
                type: string
                example: "The server is running ╰(*°▽°*)╯"

  /accounts:
    get:
      operationId: get_all_accounts
      description: Get all accounts
      summary: Get all accounts
      tags: [ 'Accounts' ]
      responses:
        '200':
          description: The list of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountBase'
    post:
      operationId: create_accounts
      description: Create new accounts
      summary: Create new accounts
      tags: [ 'Accounts' ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AccountCreate'
      responses:
        '201':
          description: The list of created accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountBase'

components:
  schemas:
    Account:
      allOf:
        - $ref: '#/components/schemas/AccountBase'
        - $ref: '#/components/schemas/Password'

    AccountBase:
      allOf:
        - $ref: '#/components/schemas/Id'
        - $ref: '#/components/schemas/Username'
        - $ref: '#/components/schemas/Email'

    AccountCreate:
      allOf:
        - $ref: '#/components/schemas/Username'
        - $ref: '#/components/schemas/Email'
        - $ref: '#/components/schemas/Password'

    Id:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426655440000"

    Username:
      type: object
      properties:
        username:
          type: string
          example: "john_doe"

    Email:
      type: object
      properties:
        email:
          type: string
          format: email
          example: "john@anonymous.user"

    Password:
      type: object
      properties:
        password:
          type: string
          example: "super duper hyper mega secret password you'll never guess"