# Generated by Django 5.1.2 on 2024-11-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='face',
            old_name='account',
            new_name='user',
        ),
        migrations.AddField(
            model_name='face',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/reference_images/'),
        ),
    ]
